# Generated by Django 4.0.4 on 2022-05-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('photoFile', models.FileField(upload_to='')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('studyId', models.AutoField(primary_key=True, serialize=False)),
                ('institutionName', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('languageId', models.AutoField(primary_key=True, serialize=False)),
                ('languageName', models.CharField(max_length=50)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experienceId', models.AutoField(primary_key=True, serialize=False)),
                ('experienceName', models.CharField(max_length=200)),
                ('experienceDescription', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactId', models.AutoField(primary_key=True, serialize=False)),
                ('contactType', models.CharField(max_length=150)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('awardId', models.AutoField(primary_key=True, serialize=False)),
                ('awardName', models.CharField(max_length=100)),
                ('awardDescription', models.CharField(max_length=500)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
