# Generated by Django 4.0.4 on 2022-05-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('infoId', models.AutoField(primary_key=True, serialize=False)),
                ('infoName', models.CharField(max_length=100)),
                ('infoDescription', models.CharField(max_length=500)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
