# Generated by Django 4.0.4 on 2022-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_otherinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photoFile',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
