# Generated by Django 4.0.4 on 2022-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_person_photofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactDescription',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='photoFile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
