# Generated by Django 4.0.4 on 2022-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact_contactdescription_alter_person_photofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='languageLevel',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
