# Generated by Django 4.0.4 on 2022-05-23 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_language_languagelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=1500)),
                ('projectTechnologies', models.CharField(max_length=500)),
                ('projectImage', models.ImageField(upload_to='images/')),
                ('projectLink', models.CharField(max_length=500)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
